### ISSUE TITLE
Escrever a premissa do jogo

### ISSUE THREAD

**Issue by Jader-T** [darkzone2/egg-clicker#2]

**Comment by BigHouse29** [comment]
Em Dragon Hatcher, você é o último senhor dos dragões e tem uma única missão, rachar ovos de dragões. Ao longo da sua missão de rachar ovos, você ganhará dinheiro que poderá usar para fazer upgrades nas suas ferramentas para ajudar na sua missão.

**Comment by netindev** [comment]
Feito.
