### ISSUE TITLE
Escolher o estilo do jogo

### ISSUE THREAD

**Issue by Jader-T** [darkzone2/egg-clicker#3]

**Comment by BigHouse29** [comment]
O jogo será de um estilo clicker, onde o jogador deverá clicar no último ovo de dinossauro existente. O jogado poderá usar pontos ganhos ao clicar para comprar itens que aumentam a taxa de cliques, até chegar em (um valor escolhido) cliques, onde então o último dinossauro do planeta terra nascerá.

**Comment by Jader-T** [comment]
Será um jogo no estilo Clicker.
